const api='/api/account/';
const $=s=>document.querySelector(s);
const status=(s,bad=false)=>{const el=$('#status');el.textContent=s;el.style.color=bad?'#b42318':'#087b68'};
async function request(action,data){const r=await fetch(api+action,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw new Error(out.error||'Request failed');return out;}
async function refresh(){const r=await fetch(api+'me',{credentials:'same-origin'});if(!r.ok)return;render(await r.json());}
function render(user){$('#auth').hidden=true;$('#dashboard').hidden=false;$('#identity').textContent=user.email+' · '+(user.role==='admin'?'Administrator':user.plan.toUpperCase());$('#features').replaceChildren();for(const item of user.features){const a=document.createElement('a');a.href=item.url;a.className='feature';a.textContent=item.name+' →';$('#features').append(a)}if(user.role==='admin'){$('#upgrade').hidden=true;$('#admin-note').hidden=false}else{$('#upgrade').hidden=false;$('#admin-note').hidden=true}}
$('#auth').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const action=document.body.dataset.admin==='true'?'admin-login':$('#mode').value;const user=await request(action,{email:f.get('email'),password:f.get('password')});render(user);status('Signed in.')}catch(err){status(err.message,true)}});
$('#logout').onclick=async()=>{await request('logout',{});location.reload()};
for(const button of document.querySelectorAll('[data-plan]'))button.onclick=async()=>{try{const order=await request('order',{plan:button.dataset.plan});if(!window.Razorpay){status('Payment checkout did not load.',true);return}new Razorpay({key:order.key,amount:order.amount,currency:'INR',order_id:order.order_id,name:'Automation In Trade',description:order.plan+' package',handler:async payment=>{try{const user=await request('verify',payment);render(user);status('Payment verified. Your plan is active.')}catch(err){status(err.message+' Contact support with your payment ID.',true)}}}).open()}catch(err){status(err.message,true)}};
refresh().catch(()=>status('Could not load your account.',true));
